
[styles]

[styles.battery]
high_battery_color = "#9FDFB5"
low_battery_color = "#F994A4"
medium_battery_color = "#F6DDB1"

[styles.cpu]
all_entry_color = "#DED3FD"
avg_entry_color = "#7BE5CC"
cpu_core_colors = [
  "#B7A5EE",
  "#BEBDFA",
  "#9FDFB5",
  "#F6DDB1",
  "#EAB9F9",
  "#6DD9C0",
  "#F3B395",
  "#B99AF4",
  "#86BDF9",
  "#BFA2EC",
  "#BCF0C9",
  "#F3E5CE",
  "#F5A3AF",
  "#A3E0CB",
  "#40C4C4",
  "#E4BAF7",
]

[styles.graphs]
graph_color = "#4C425C"
legend_text = { color = "#A79BCF" }

[styles.memory]
arc_color = "#6DD9C0"
cache_color = "#78639C"
ram_color = "#9FDFB5"
swap_color = "#F6DDB1"
gpu_colors = [
  "#BFA2EC",
  "#86BDF9",
  "#F3B395",
  "#E4BAF7",
  "#B7A5EE",
  "#BEBDFA",
]

[styles.network]
rx_color = "#9FDFB5"
rx_total_color = "#BCF0C9"
tx_color = "#B7A5EE"
tx_total_color = "#BFA2EC"

[styles.tables]
headers = { color = "#DED3FD", bold = true }

[styles.widgets]
border_color = "#4C425C"
disabled_text = { color = "#6C5A8C" }
selected_border_color = "#B1B0E8"
selected_text = { color = "#FFFFFF", bg_color = "#564D84" }
text = { color = "#A79BCF" }
widget_title = { color = "#DED3FD", bold = true }
